### ISSUE TITLE
tcpdump -r error

### ISSUE THREAD

**Issue by danseo-reisys** [tdihp/dspcap#8]
Hello.

we are not able to use wireshark on our program.
tcpdump -r throwing errors.   any suggestion?

tcpdump -r 2023-11-08T17:33.aks-agentpool-33540062-vmss00000R.pcap
reading from file 2023-11-08T17:33.aks-agentpool-33540062-vmss00000R.pcap, link-type 276
tcpdump: unknown data link type 276

Thanks.

**Comment by tdihp** [comment]
Hi @danseo-reisys , link type 276 is LINKTYPE_LINUX_SLL2 which is a new link layer protocol, probably your tcpdump version is not compatible with the newer capture, as newer tcpdump uses newer versions of libpcap-ng which uses this new format when captures with `tcpdump -iany`. Have you tried a newer tcpdump version?

**Comment by tdihp** [comment]
Closing for now. Do let us know if any updates.
